version: '3.2'
volumes:
  post_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - post_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: jetdj/foodgram:latest
    restart: always
    command: sh -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./static:/code/static
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.4
    volumes:
      - ./static:/code/static
      - ./media:/code/media
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web
