# Generated by Django 3.1.3 on 2020-12-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201201_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
