# Generated by Django 3.1.3 on 2020-12-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='view',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
