# Generated by Django 3.1.3 on 2020-12-18 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201218_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='is_main',
            new_name='is_basic',
        ),
    ]
